// Package view ports the clock demo's sub-interfaces. The upstream
// Ui_FocusInterface.py / Ui_StopWatchInterface.py files were generated by
// pyuic5 from .ui files; they are translated here directly into Go widget
// construction code, and the resource_rc.py images are loaded from the
// clock/resource package (go:embed).
package view

import (
	qt "github.com/mappu/miqt/qt"

	"github.com/famei/gofluent/common"
	"github.com/famei/gofluent/components/date_time"
	"github.com/famei/gofluent/components/widgets"
	"github.com/famei/gofluent/examples/window/clock/resource"
)

// FocusInterface is the "专注时段" (focus session) sub-interface.
type FocusInterface struct {
	*qt.QWidget

	progressCard *widgets.CardWidget
	focusCard    *widgets.CardWidget
	taskCard     *widgets.CardWidget
	taskCard1    *widgets.CardWidget
	taskCard2    *widgets.CardWidget
	taskCard3    *widgets.CardWidget

	progressIcon      *widgets.IconWidget
	focusCardIcon     *widgets.IconWidget
	taskCardIcon      *widgets.IconWidget
	taskIcon1         *widgets.IconWidget
	taskIcon2         *widgets.IconWidget
	taskIcon3         *widgets.IconWidget
	pinButton         *widgets.TransparentToolButton
	moreButton        *widgets.TransparentToolButton
	editButton        *widgets.TransparentToolButton
	addTaskButton     *widgets.TransparentToolButton
	moreTaskButton    *widgets.TransparentToolButton
	startFocusButton  *widgets.PrimaryPushButton
	skipRelaxCheckBox *widgets.CheckBox
	timePicker        *date_time.TimePicker
	progressRing      *widgets.ProgressRing

	dailyProgressLabel          *widgets.StrongBodyLabel
	yesterdayLabel              *widgets.BodyLabel
	yesterdayTimeLabel          *widgets.LargeTitleLabel
	minuteLabel1                *widgets.BodyLabel
	targetLabel                 *widgets.SubtitleLabel
	finishTimeLabel             *widgets.BodyLabel
	continousComplianceDayLabel *widgets.BodyLabel
	compianceDayLabel           *widgets.LargeTitleLabel
	dayLabel                    *widgets.BodyLabel
	focusPeriodLabel            *widgets.StrongBodyLabel
	prepareFocusLabel           *widgets.SubtitleLabel
	hintLabel                   *widgets.BodyLabel
	bottomHintLabel             *widgets.BodyLabel
	taskLabel                   *widgets.StrongBodyLabel
	hintLabel2                  *widgets.BodyLabel
	taskLabel1                  *widgets.BodyLabel
	taskLabel2                  *widgets.BodyLabel
	taskLabel3                  *widgets.BodyLabel
}

// NewFocusInterface builds the focus interface widget.
func NewFocusInterface(parent *qt.QWidget) *FocusInterface {
	w := &FocusInterface{QWidget: qt.NewQWidget(parent)}
	w.SetObjectName("FocusInterface")

	w.buildProgressCard()
	w.buildFocusCard()
	w.buildTaskCard()
	w.buildGrid()
	w.retranslate()

	// set the icon of the buttons
	w.pinButton.SetIcon(common.Pin)
	w.moreButton.SetIcon(common.More)
	w.startFocusButton.SetIcon(common.PowerButton)
	w.editButton.SetIcon(common.Edit)
	w.addTaskButton.SetIcon(common.Add)
	w.moreTaskButton.SetIcon(common.More)
	w.taskIcon1.SetIcon(widgets.InfoBarIconSuccess)
	w.taskIcon2.SetIcon(widgets.InfoBarIconWarning)
	w.taskIcon3.SetIcon(widgets.InfoBarIconWarning)

	common.SetFont(w.progressRing.QWidget, 16, int(qt.QFont__Normal))

	// add drop shadow effects to the cards
	setShadowEffect(w.focusCard.QWidget)
	setShadowEffect(w.progressCard.QWidget)
	setShadowEffect(w.taskCard.QWidget)
	return w
}

func (w *FocusInterface) buildProgressCard() {
	w.progressCard = widgets.NewCardWidget(w.QWidget)
	w.progressCard.SetMinimumSize2(380, 410)
	w.progressCard.SetMaximumSize2(600, 410)
	w.progressCard.SetObjectName("progressCard")

	vLayout4 := qt.NewQVBoxLayout(w.progressCard.QWidget)
	vLayout2 := qt.NewQVBoxLayout2()

	// header row: icon + label + edit button
	hLayout4 := qt.NewQHBoxLayout2()
	hLayout4.SetContentsMargins(5, -1, -1, -1)
	w.progressIcon = widgets.NewIconWidgetIcon(resource.Tips(), w.progressCard.QWidget)
	w.progressIcon.SetMinimumSize2(18, 18)
	w.progressIcon.SetMaximumSize2(18, 18)
	w.progressIcon.SetObjectName("progressIcon")
	hLayout4.AddWidget(w.progressIcon.QWidget)
	hLayout4.AddSpacing(2)
	w.dailyProgressLabel = widgets.NewStrongBodyLabelText("", w.progressCard.QWidget)
	w.dailyProgressLabel.SetObjectName("dailyProgressLabel")
	hLayout4.AddWidget(w.dailyProgressLabel.QWidget)
	hLayout4.AddStretchWithStretch(1)
	w.editButton = widgets.NewTransparentToolButton(w.progressCard.QWidget)
	w.editButton.SetObjectName("editButton")
	hLayout4.AddWidget3(w.editButton.QWidget, 0, qt.AlignRight)
	vLayout2.AddLayout(hLayout4.QLayout)

	// three columns: yesterday / ring / compliance
	hLayout5 := qt.NewQHBoxLayout2()

	vLayout5 := qt.NewQVBoxLayout2()
	vLayout5.AddStretchWithStretch(1)
	w.yesterdayLabel = widgets.NewBodyLabelText("", w.progressCard.QWidget)
	w.yesterdayLabel.SetObjectName("yesterdayLabel")
	vLayout5.AddWidget3(w.yesterdayLabel.QWidget, 0, qt.AlignHCenter|qt.AlignVCenter)
	w.yesterdayTimeLabel = widgets.NewLargeTitleLabelText("", w.progressCard.QWidget)
	w.yesterdayTimeLabel.SetObjectName("yesterdayTimeLabel")
	vLayout5.AddWidget3(w.yesterdayTimeLabel.QWidget, 0, qt.AlignHCenter|qt.AlignVCenter)
	w.minuteLabel1 = widgets.NewBodyLabelText("", w.progressCard.QWidget)
	w.minuteLabel1.SetObjectName("minuteLabel1")
	vLayout5.AddWidget3(w.minuteLabel1.QWidget, 0, qt.AlignHCenter|qt.AlignVCenter)
	vLayout5.AddStretchWithStretch(1)
	hLayout5.AddLayout(vLayout5.QLayout)

	vLayout10 := qt.NewQVBoxLayout2()
	vLayout10.AddStretchWithStretch(1)
	w.targetLabel = widgets.NewSubtitleLabelText("", w.progressCard.QWidget)
	w.targetLabel.SetAlignment(qt.AlignCenter)
	w.targetLabel.SetObjectName("targetLabel")
	vLayout10.AddWidget(w.targetLabel.QWidget)
	w.progressRing = widgets.NewProgressRing(w.progressCard.QWidget, false)
	w.progressRing.SetMinimumSize2(150, 150)
	w.progressRing.SetMaximumSize2(220, 220)
	w.progressRing.SetMaximum(24)
	w.progressRing.SetProperty("value", qt.NewQVariant7(10))
	w.progressRing.SetAlignment(qt.AlignCenter)
	w.progressRing.SetTextVisible(true)
	w.progressRing.SetFormat("目标 %v 小时")
	w.progressRing.SetVal(10.0)
	w.progressRing.SetStrokeWidth(15)
	w.progressRing.SetObjectName("progressRing")
	vLayout10.AddWidget(w.progressRing.QWidget)
	vLayout10.AddSpacing(3)
	w.finishTimeLabel = widgets.NewBodyLabelText("", w.progressCard.QWidget)
	w.finishTimeLabel.SetObjectName("finishTimeLabel")
	vLayout10.AddWidget3(w.finishTimeLabel.QWidget, 0, qt.AlignHCenter)
	vLayout10.AddStretchWithStretch(1)
	vLayout10.SetStretch(2, 1)
	hLayout5.AddLayout(vLayout10.QLayout)

	vLayout6 := qt.NewQVBoxLayout2()
	vLayout6.AddStretchWithStretch(1)
	w.continousComplianceDayLabel = widgets.NewBodyLabelText("", w.progressCard.QWidget)
	w.continousComplianceDayLabel.SetObjectName("continousComplianceDayLabel")
	vLayout6.AddWidget3(w.continousComplianceDayLabel.QWidget, 0, qt.AlignHCenter|qt.AlignVCenter)
	w.compianceDayLabel = widgets.NewLargeTitleLabelText("", w.progressCard.QWidget)
	w.compianceDayLabel.SetObjectName("compianceDayLabel")
	vLayout6.AddWidget3(w.compianceDayLabel.QWidget, 0, qt.AlignHCenter)
	w.dayLabel = widgets.NewBodyLabelText("", w.progressCard.QWidget)
	w.dayLabel.SetObjectName("dayLabel")
	vLayout6.AddWidget3(w.dayLabel.QWidget, 0, qt.AlignHCenter)
	vLayout6.AddStretchWithStretch(1)
	hLayout5.AddLayout(vLayout6.QLayout)

	hLayout5.SetStretch(0, 1)
	hLayout5.SetStretch(1, 2)
	hLayout5.SetStretch(2, 1)
	vLayout2.AddLayout(hLayout5.QLayout)

	vLayout4.AddLayout(vLayout2.QLayout)
}

func (w *FocusInterface) buildFocusCard() {
	w.focusCard = widgets.NewCardWidget(w.QWidget)
	w.focusCard.SetMinimumSize2(380, 410)
	w.focusCard.SetMaximumSize2(600, 410)
	w.focusCard.SetStyleSheet("")
	w.focusCard.SetObjectName("focusCard")

	vLayout3 := qt.NewQVBoxLayout(w.focusCard.QWidget)
	vLayout := qt.NewQVBoxLayout2()

	hLayout2 := qt.NewQHBoxLayout2()
	hLayout2.SetContentsMargins(5, -1, -1, -1)
	w.focusCardIcon = widgets.NewIconWidgetIcon(resource.Alarms(), w.focusCard.QWidget)
	w.focusCardIcon.SetMinimumSize2(20, 20)
	w.focusCardIcon.SetMaximumSize2(20, 20)
	w.focusCardIcon.SetObjectName("focusCardIcon")
	hLayout2.AddWidget(w.focusCardIcon.QWidget)
	w.focusPeriodLabel = widgets.NewStrongBodyLabelText("", w.focusCard.QWidget)
	w.focusPeriodLabel.SetObjectName("focusPeriodLabel")
	hLayout2.AddWidget(w.focusPeriodLabel.QWidget)
	hLayout2.AddStretchWithStretch(1)
	w.pinButton = widgets.NewTransparentToolButton(w.focusCard.QWidget)
	w.pinButton.SetObjectName("pinButton")
	hLayout2.AddWidget(w.pinButton.QWidget)
	w.moreButton = widgets.NewTransparentToolButton(w.focusCard.QWidget)
	w.moreButton.SetObjectName("moreButton")
	hLayout2.AddWidget(w.moreButton.QWidget)
	vLayout.AddLayout(hLayout2.QLayout)

	vLayout.AddStretchWithStretch(1)

	w.prepareFocusLabel = widgets.NewSubtitleLabelText("", w.focusCard.QWidget)
	w.prepareFocusLabel.SetAlignment(qt.AlignCenter)
	w.prepareFocusLabel.SetObjectName("prepareFocusLabel")
	vLayout.AddWidget(w.prepareFocusLabel.QWidget)

	hLayout6 := qt.NewQHBoxLayout2()
	hLayout6.SetContentsMargins(15, 10, 15, -1)
	w.hintLabel = widgets.NewBodyLabelText("", w.focusCard.QWidget)
	w.hintLabel.SetAlignment(qt.AlignCenter)
	w.hintLabel.SetWordWrap(true)
	w.hintLabel.SetProperty("lightColor", qt.NewQVariant14("#606060"))
	w.hintLabel.SetProperty("darkColor", qt.NewQVariant14("#cecece"))
	w.hintLabel.SetObjectName("hintLabel")
	hLayout6.AddWidget(w.hintLabel.QWidget)
	vLayout.AddLayout(hLayout6.QLayout)

	vLayout.AddSpacing(20)

	w.timePicker = date_time.NewTimePicker(w.focusCard.QWidget, true)
	w.timePicker.SetSecondVisible(true)
	w.timePicker.SetObjectName("timePicker")
	vLayout.AddWidget3(w.timePicker.QWidget, 0, qt.AlignHCenter)

	vLayout.AddSpacing(10)

	w.bottomHintLabel = widgets.NewBodyLabelText("", w.focusCard.QWidget)
	w.bottomHintLabel.SetAlignment(qt.AlignCenter)
	w.bottomHintLabel.SetObjectName("bottomHintLabel")
	vLayout.AddWidget3(w.bottomHintLabel.QWidget, 0, qt.AlignHCenter)

	vLayout.AddSpacing(10)

	w.skipRelaxCheckBox = widgets.NewCheckBox(w.focusCard.QWidget)
	w.skipRelaxCheckBox.SetEnabled(true)
	w.skipRelaxCheckBox.SetObjectName("skipRelaxCheckBox")
	vLayout.AddWidget3(w.skipRelaxCheckBox.QWidget, 0, qt.AlignHCenter)

	vLayout.AddSpacing(20)

	w.startFocusButton = widgets.NewPrimaryPushButton(w.focusCard.QWidget)
	w.startFocusButton.SetAutoDefault(true)
	w.startFocusButton.SetObjectName("startFocusButton")
	vLayout.AddWidget3(w.startFocusButton.QWidget, 0, qt.AlignHCenter)

	vLayout.AddStretchWithStretch(1)
	vLayout3.AddLayout(vLayout.QLayout)
}

func (w *FocusInterface) buildTaskCard() {
	w.taskCard = widgets.NewCardWidget(w.QWidget)
	w.taskCard.SetMinimumSize2(370, 0)
	w.taskCard.SetMaximumSize2(600, 395)
	w.taskCard.SetObjectName("taskCard")

	vLayout8 := qt.NewQVBoxLayout(w.taskCard.QWidget)
	vLayout7 := qt.NewQVBoxLayout2()
	vLayout7.SetContentsMargins(8, -1, -1, -1)

	hLayout7 := qt.NewQHBoxLayout2()
	w.taskCardIcon = widgets.NewIconWidgetIcon(resource.Todo(), w.taskCard.QWidget)
	w.taskCardIcon.SetMinimumSize2(18, 18)
	w.taskCardIcon.SetMaximumSize2(18, 18)
	w.taskCardIcon.SetObjectName("taskCardIcon")
	hLayout7.AddWidget(w.taskCardIcon.QWidget)
	hLayout7.AddSpacing(2)
	w.taskLabel = widgets.NewStrongBodyLabelText("", w.taskCard.QWidget)
	w.taskLabel.SetObjectName("taskLabel")
	hLayout7.AddWidget(w.taskLabel.QWidget)
	hLayout7.AddStretchWithStretch(1)
	w.addTaskButton = widgets.NewTransparentToolButton(w.taskCard.QWidget)
	w.addTaskButton.SetObjectName("addTaskButton")
	hLayout7.AddWidget(w.addTaskButton.QWidget)
	w.moreTaskButton = widgets.NewTransparentToolButton(w.taskCard.QWidget)
	w.moreTaskButton.SetObjectName("moreTaskButton")
	hLayout7.AddWidget(w.moreTaskButton.QWidget)
	vLayout7.AddLayout(hLayout7.QLayout)

	vLayout7.AddSpacing(3)

	w.hintLabel2 = widgets.NewBodyLabelText("", w.taskCard.QWidget)
	w.hintLabel2.SetProperty("lightColor", qt.NewQVariant14("#606060"))
	w.hintLabel2.SetProperty("darkColor", qt.NewQVariant14("#cecece"))
	w.hintLabel2.SetObjectName("hintLabel_2")
	vLayout7.AddWidget(w.hintLabel2.QWidget)

	vLayout9 := qt.NewQVBoxLayout2()
	vLayout9.SetContentsMargins(-1, -1, 7, -1)

	w.taskCard1 = newTaskCard(w.taskCard.QWidget, "taskCard1")
	w.taskIcon1 = widgets.NewIconWidget(w.taskCard1.QWidget)
	configureTaskIcon(w.taskIcon1, "taskIcon1")
	addTaskRow(w.taskCard1, w.taskIcon1, &w.taskLabel1, "taskLabel1", true)
	vLayout9.AddWidget(w.taskCard1.QWidget)

	w.taskCard2 = newTaskCard(w.taskCard.QWidget, "taskCard2")
	w.taskIcon2 = widgets.NewIconWidget(w.taskCard2.QWidget)
	configureTaskIcon(w.taskIcon2, "taskIcon2")
	addTaskRow(w.taskCard2, w.taskIcon2, &w.taskLabel2, "taskLabel2", false)
	vLayout9.AddWidget(w.taskCard2.QWidget)

	w.taskCard3 = newTaskCard(w.taskCard.QWidget, "taskCard3")
	w.taskIcon3 = widgets.NewIconWidget(w.taskCard3.QWidget)
	configureTaskIcon(w.taskIcon3, "taskIcon3")
	addTaskRow(w.taskCard3, w.taskIcon3, &w.taskLabel3, "taskLabel3", false)
	vLayout9.AddWidget(w.taskCard3.QWidget)

	vLayout7.AddLayout(vLayout9.QLayout)
	vLayout7.AddStretchWithStretch(1)
	vLayout8.AddLayout(vLayout7.QLayout)
}

func (w *FocusInterface) buildGrid() {
	hLayout3 := qt.NewQHBoxLayout(w.QWidget)
	grid := qt.NewQGridLayout2()
	grid.SetContentsMargins(20, 40, 20, 20)
	grid.SetSpacing(12)

	grid.AddWidget3(w.progressCard.QWidget, 0, 1, 1, 1)
	grid.AddWidget3(w.focusCard.QWidget, 0, 0, 1, 1)
	grid.AddWidget3(w.taskCard.QWidget, 1, 0, 1, 1)
	grid.SetColumnStretch(0, 1)
	grid.SetColumnStretch(1, 1)

	hLayout3.AddLayout(grid.QLayout)
}

func (w *FocusInterface) retranslate() {
	w.dailyProgressLabel.SetText("每日进度")
	w.yesterdayLabel.SetText("昨天")
	w.yesterdayTimeLabel.SetText("3")
	w.minuteLabel1.SetText("分钟")
	w.targetLabel.SetText("今日计划")
	w.finishTimeLabel.SetText("已完成：0 分钟")
	w.continousComplianceDayLabel.SetText("连续达标日")
	w.compianceDayLabel.SetText("5")
	w.dayLabel.SetText("天")
	w.focusPeriodLabel.SetText("专注时段")
	w.prepareFocusLabel.SetText("准备专注")
	w.hintLabel.SetText("我们将在每个会话期间关闭通知和应用警报。对于较长的会话，我们将添加简短的休息时间，以便你可以恢复精力。")
	w.bottomHintLabel.SetText("你将没有休息时间。")
	w.skipRelaxCheckBox.SetText("跳过休息")
	w.startFocusButton.SetText("启动专注时段")
	w.taskLabel.SetText("任务")
	w.hintLabel2.SetText("为会话选择任务")
	w.taskLabel1.SetText("全军出🐔，誓死保卫鸽鸽🏀！！")
	w.taskLabel2.SetText("上传我家 aiko 的 MV『シアワセ』")
	w.taskLabel3.SetText("下载我家 aiko 的新歌『荒れた唇は恋を失くす』")
}

// newTaskCard builds a 44px high inner task card.
func newTaskCard(parent *qt.QWidget, objectName string) *widgets.CardWidget {
	card := widgets.NewCardWidget(parent)
	card.SetMinimumSize2(0, 44)
	card.SetMaximumSize2(16777215, 44)
	card.SetObjectName(objectName)
	return card
}

// configureTaskIcon sizes an inner task icon widget.
func configureTaskIcon(icon *widgets.IconWidget, objectName string) {
	icon.SetMinimumSize2(16, 16)
	icon.SetMaximumSize2(16, 16)
	icon.SetObjectName(objectName)
}

// addTaskRow builds the layout of a single inner task row.
func addTaskRow(card *widgets.CardWidget, icon *widgets.IconWidget, label **widgets.BodyLabel, objectName string, strikeOut bool) {
	hLayout9 := qt.NewQHBoxLayout(card.QWidget)
	hLayout9.SetContentsMargins(15, -1, -1, -1)

	hLayout8 := qt.NewQHBoxLayout2()
	hLayout8.AddWidget(icon.QWidget)
	hLayout9.AddLayout(hLayout8.QLayout)

	l := widgets.NewBodyLabelText("", card.QWidget)
	l.SetProperty("pixelFontSize", qt.NewQVariant7(14))
	if strikeOut {
		l.SetProperty("strikeOut", qt.NewQVariant11(true))
	}
	l.SetObjectName(objectName)
	*label = l
	hLayout9.AddWidget(l.QWidget)
	hLayout9.AddStretchWithStretch(1)
}

// setShadowEffect attaches a soft drop shadow to a card.
func setShadowEffect(card *qt.QWidget) {
	effect := qt.NewQGraphicsDropShadowEffect2(card.QObject)
	effect.SetColor(qt.NewQColor11(0, 0, 0, 15))
	effect.SetBlurRadius(10)
	effect.SetOffset2(0, 0)
	card.SetGraphicsEffect(effect.QGraphicsEffect)
}
